replicaCount: 1
image:
  repository: ghcr.io/equal-vote/alaska-rcv
  tag: "sha-683cb8c"
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  hosts:
    - host: realrcv.equal.vote
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: alaska-rcv-tls
      hosts:
        - realrcv.equal.vote
env: []
service:
  port: 3000
